# Generated by Django 4.2.7 on 2025-05-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_refreshtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
