# Generated by Django 4.2.7 on 2025-05-03 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_refreshtoken_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refreshtoken',
            old_name='deactivation_time',
            new_name='deactivation_at',
        ),
    ]
