# Generated by Django 4.2.7 on 2025-11-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
