# Generated by Django 4.2.7 on 2025-12-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_uploadedfile_keywords'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='financialproduct',
            index=models.Index(fields=['created_by'], name='accounts_fi_created_5d542c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialproduct',
            index=models.Index(fields=['status'], name='accounts_fi_status_e7f584_idx'),
        ),
        migrations.AddIndex(
            model_name='financialproduct',
            index=models.Index(fields=['is_deleted'], name='accounts_fi_is_dele_531064_idx'),
        ),
        migrations.AddIndex(
            model_name='financialproduct',
            index=models.Index(fields=['created_by', 'is_deleted'], name='accounts_fi_created_3486a9_idx'),
        ),
        migrations.AddIndex(
            model_name='financialproduct',
            index=models.Index(fields=['created_by', 'status'], name='accounts_fi_created_c16822_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['created_by'], name='accounts_le_created_1311c0_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['status'], name='accounts_le_status_b58f91_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['transaction_date'], name='accounts_le_transac_60ee54_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['is_deleted'], name='accounts_le_is_dele_c568e1_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['created_by', 'is_deleted'], name='accounts_le_created_fe9842_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['created_by'], name='accounts_re_created_17f305_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['reminder_date'], name='accounts_re_reminde_5e1659_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['is_deleted'], name='accounts_re_is_dele_e4de85_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['frequency'], name='accounts_re_frequen_be3a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['created_by', 'is_deleted'], name='accounts_re_created_d4aab1_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['created_by', 'reminder_date'], name='accounts_re_created_e002e4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by'], name='accounts_ta_created_f6c172_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='accounts_ta_status_7456d2_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['complete_by_date'], name='accounts_ta_complet_668072_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_deleted'], name='accounts_ta_is_dele_b96efd_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'is_deleted'], name='accounts_ta_created_b9f0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'status'], name='accounts_ta_created_13ad47_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['date'], name='accounts_tr_date_4ebe57_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by'], name='accounts_tr_created_89ad51_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['is_deleted'], name='accounts_tr_is_dele_18853c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='accounts_tr_status_9c451f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='accounts_tr_type_799744_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category'], name='accounts_tr_categor_f21d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by', 'is_deleted'], name='accounts_tr_created_658c96_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by', 'is_deleted', 'date'], name='accounts_tr_created_4453ff_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by', 'is_deleted', 'status'], name='accounts_tr_created_ee1f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
    ]
