# Generated by Django 4.2.7 on 2026-01-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_financialproduct_accounts_fi_created_5d542c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique module identifier (e.g., 'TRANSACTION', 'FINANCE')", max_length=50, unique=True)),
                ('title', models.CharField(help_text='Display title shown to users', max_length=100)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-credit-card')", max_length=50)),
                ('description', models.TextField(help_text='Module description displayed on utilities page')),
                ('url_pattern', models.CharField(help_text="URL path for module (e.g., '/transaction-detail/')", max_length=200)),
                ('display_order', models.IntegerField(default=0, help_text='Sort order in UI (lower numbers appear first)')),
                ('access_type', models.CharField(choices=[('PUBLIC', 'All Users'), ('CONFIG', 'Config-Based'), ('ADMIN', 'Admin Only')], default='CONFIG', help_text='Access control type: PUBLIC (all users), CONFIG (specific users), ADMIN (admin only)', max_length=20)),
                ('allowed_users', models.TextField(blank=True, help_text="Comma-separated usernames (if access_type=CONFIG). Use '*' for all users")),
                ('is_active', models.BooleanField(default=True, help_text='Module enabled/disabled toggle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Utility Module',
                'verbose_name_plural': 'Utility Modules',
                'ordering': ['display_order', 'title'],
                'indexes': [models.Index(fields=['key'], name='accounts_ut_key_fd627b_idx'), models.Index(fields=['is_active'], name='accounts_ut_is_acti_226a8b_idx'), models.Index(fields=['display_order'], name='accounts_ut_display_8f88e3_idx'), models.Index(fields=['is_active', 'display_order'], name='accounts_ut_is_acti_71163f_idx')],
            },
        ),
    ]
