# Generated by Django 4.2.7 on 2026-01-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_seed_utility_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitymodule',
            name='allowed_users_list',
            field=models.ManyToManyField(blank=True, help_text='Select specific users who can access this module', related_name='accessible_modules', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='utilitymodule',
            name='allowed_users',
            field=models.TextField(blank=True, help_text="Legacy field: Use '*' for all users, or leave blank to use the user selection below"),
        ),
    ]
