# Generated by Django 4.2.7 on 2026-01-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_utilitymodule_allowed_users_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilitymodule',
            name='allowed_users',
        ),
    ]
