# Generated by Django 4.2.7 on 2026-01-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_utilitymodule_allowed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitymodule',
            name='show_on_landing',
            field=models.BooleanField(default=False, help_text='Display this module on the landing page (for non-logged-in users)'),
        ),
    ]
