# Generated by Django 4.2.7 on 2026-01-03 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_utilitymodule_show_on_landing'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitymodule',
            name='landing_description',
            field=models.TextField(blank=True, help_text='Description to show on landing page (if different from main description)'),
        ),
        migrations.AddField(
            model_name='utilitymodule',
            name='landing_title',
            field=models.CharField(blank=True, help_text='Title to show on landing page (if different from main title)', max_length=100),
        ),
    ]
