# Generated by Django 6.0 on 2026-01-03 09:34

from django.db import migrations





def migrate_users_forward(apps, schema_editor):
    LegacyUser = apps.get_model('accounts', 'User')
    AuthUser = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('accounts', 'UserProfile')
    
    for legacy_user in LegacyUser.objects.all():
        # Handle potential username/email conflicts
        username = legacy_user.username
        if AuthUser.objects.filter(username=username).exists():
            print(f"Skipping duplicate username: {username}")
            continue
            
        if AuthUser.objects.filter(email=legacy_user.email).exists():
            print(f"Skipping duplicate email: {legacy_user.email}")
            continue

        # Create Auth User
        # Note: Legacy passwords are unhashed or hashed differently? 
        # Checking models.py, they seem to be plain text or custom hash in some places, 
        # but view_auth.py uses make_password. We will copy as is.
        # If they are not compatible with Django's default hasher, users might need to reset password.
        # Based on view_auth.py: user.password = make_password(password)
        # So they are likely standard Django hashes (PBKDF2).
        
        auth_user = AuthUser.objects.create(
            username=username,
            email=legacy_user.email,
            password=legacy_user.password,
            first_name=legacy_user.name, # Storing full name in first_name for now
            is_active=True,
            date_joined=legacy_user.created_at
        )
        
        # Create Profile
        UserProfile.objects.create(
            user=auth_user,
            profile_picture=legacy_user.profile_picture,
            created_at=legacy_user.created_at,
            updated_at=legacy_user.updated_at
        )

def migrate_users_backward(apps, schema_editor):
    # We don't want to delete AuthUsers on rollback as it might delete superusers created independently
    # But strictly speaking, a reverse should undo the operations. 
    # For safety, let's only delete UserProfiles which cascades to nothing critical (except the profile itself).
    # If we really want to be clean, we'd track which users were created.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_options_userprofile'),
    ]

    operations = [
        migrations.RunPython(migrate_users_forward, migrate_users_backward),
    ]

