# Generated by Django 6.0 on 2026-01-03 09:36

from django.db import migrations





def migrate_data_forward(apps, schema_editor):
    AuthUser = apps.get_model('auth', 'User')
    
    # Models to migrate
    models_with_created_by = [
        apps.get_model('accounts', 'FinancialProduct'),
        apps.get_model('accounts', 'Transaction'),
        apps.get_model('accounts', 'Task'),
        apps.get_model('accounts', 'LedgerTransaction'),
        apps.get_model('accounts', 'Reminder'),
        apps.get_model('accounts', 'RefreshToken'),
    ]
    
    # Process created_by fields
    for Model in models_with_created_by:
        for obj in Model.objects.all():
            if obj.created_by:
                # Find matching auth user by username
                auth_user = AuthUser.objects.filter(username=obj.created_by.username).first()
                if auth_user:
                    obj.new_created_by = auth_user
                    obj.save()

    # Process UploadedFile (owner -> new_owner)
    UploadedFile = apps.get_model('accounts', 'UploadedFile')
    for obj in UploadedFile.objects.all():
        if obj.owner:
            auth_user = AuthUser.objects.filter(username=obj.owner.username).first()
            obj.new_owner = auth_user
            obj.save()

    # Process UtilityModule (allowed_users -> new_allowed_users_list)
    UtilityModule = apps.get_model('accounts', 'UtilityModule')
    for obj in UtilityModule.objects.all():
        old_users = obj.allowed_users_list.all()
        for old_user in old_users:
            auth_user = AuthUser.objects.filter(username=old_user.username).first()
            if auth_user:
                obj.new_allowed_users_list.add(auth_user)


def migrate_data_backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_financialproduct_new_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
    ]

