# Generated by Django 6.0 on 2026-01-03 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_migrate_fks_to_new_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialproduct',
            name='new_created_by',
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='new_created_by',
        ),
        migrations.RemoveField(
            model_name='refreshtoken',
            name='new_created_by',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='new_created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='new_created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='new_created_by',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='new_owner',
        ),
        migrations.RemoveField(
            model_name='utilitymodule',
            name='new_allowed_users_list',
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilitymodule',
            name='allowed_users_list',
            field=models.ManyToManyField(blank=True, help_text='Select specific users who can access this module', related_name='accessible_modules', to=settings.AUTH_USER_MODEL),
        ),
    ]
