# Generated by Django 6.0 on 2026-01-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_financialproduct_new_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_usernam_c0ea66_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_email_74c8d6_idx',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
