# Generated by Django 6.0 on 2026-01-04 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_user_accounts_us_usernam_c0ea66_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly'), ('CUSTOM', 'Custom (days)')], help_text='How often the task repeats', max_length=10)),
                ('interval', models.IntegerField(default=1, help_text='Repeat every X days/weeks/months/years (e.g., every 2 weeks)')),
                ('weekdays', models.JSONField(blank=True, default=list, help_text='List of weekday numbers for weekly recurrence (0=Monday, 6=Sunday)')),
                ('day_of_month', models.IntegerField(blank=True, help_text='Day of month (1-31) for monthly recurrence', null=True)),
                ('custom_days', models.IntegerField(blank=True, help_text='Number of days for custom recurrence pattern', null=True)),
                ('end_date', models.DateField(blank=True, help_text='When to stop creating recurring tasks (optional)', null=True)),
                ('max_occurrences', models.IntegerField(blank=True, help_text='Maximum number of task instances to create (optional)', null=True)),
            ],
            options={
                'verbose_name': 'Recurring Pattern',
                'verbose_name_plural': 'Recurring Patterns',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_url', models.URLField(blank=True, help_text='External link (e.g., Google Drive, Dropbox)')),
                ('name', models.CharField(help_text='Attachment name for display', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Notes about this attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Attachment',
                'verbose_name_plural': 'Task Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name (e.g., 'Work', 'Personal', 'Health')", max_length=100)),
                ('color', models.CharField(default='#6c757d', help_text="Hex color code for visual identification (e.g., '#3B82F6')", max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-briefcase')", max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which categories appear (lower first)')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Category',
                'verbose_name_plural': 'Task Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Tag name (e.g., 'urgent', 'waiting', 'quick-win')", max_length=50)),
                ('color', models.CharField(default='#6c757d', help_text='Hex color code for tag chip display', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Tag',
                'verbose_name_plural': 'Task Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for identification', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('task_title_template', models.CharField(help_text='Default task title (can include placeholders like {date})', max_length=200)),
                ('task_description_template', models.TextField(blank=True, help_text='Default task description')),
                ('default_priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=50)),
                ('default_estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('days_until_due', models.IntegerField(default=7, help_text='Number of days from creation until due date')),
                ('subtask_templates', models.JSONField(blank=True, default=list, help_text='List of subtask names to create with this template')),
                ('use_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Template',
                'verbose_name_plural': 'Task Templates',
                'ordering': ['-use_count', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='When work started')),
                ('end_time', models.DateTimeField(blank=True, help_text='When work ended (null if timer is running)', null=True)),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, help_text='Calculated duration in hours', max_digits=6)),
                ('notes', models.TextField(blank=True, help_text='Notes about what was accomplished')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time Log',
                'verbose_name_plural': 'Time Logs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority_score', 'complete_by_date', 'position'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='accounts_ta_created_f6c172_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='accounts_ta_is_dele_b96efd_idx',
        ),
        migrations.RemoveIndex(
            model_name='task',
            name='accounts_ta_created_13ad47_idx',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Actual time spent on task (in hours)', max_digits=6),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated time to complete (in hours)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this task repeats on a schedule'),
        ),
        migrations.AddField(
            model_name='task',
            name='next_occurrence_date',
            field=models.DateField(blank=True, help_text='Next date when a recurring instance will be created', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes, updates, or context'),
        ),
        migrations.AddField(
            model_name='task',
            name='occurrence_count',
            field=models.IntegerField(default=0, help_text='Number of times this recurring task has been generated'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, help_text='Parent task if this is a subtask', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='accounts.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='position',
            field=models.IntegerField(default=0, help_text='Manual sort order within a category or list'),
        ),
        migrations.AddField(
            model_name='task',
            name='priority_score',
            field=models.IntegerField(default=0, help_text='Auto-calculated priority score for smart sorting'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_parent',
            field=models.ForeignKey(blank=True, help_text='Original task if this is a recurring instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='accounts.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_datetime',
            field=models.DateTimeField(blank=True, help_text='When to send a reminder notification', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Whether reminder has been sent'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, help_text='When to start working on this task', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='complete_by_date',
            field=models.DateField(blank=True, help_text='Due date for task completion', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_on',
            field=models.DateTimeField(blank=True, help_text='When the task was completed', null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed task description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='Task title/name', max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', help_text='Task priority level', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', help_text='Current task status', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='recurring_pattern',
            field=models.ForeignKey(blank=True, help_text='Recurrence pattern for this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.recurringpattern'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(help_text='Task this attachment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.task'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, help_text='Reference to file in document manager', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.uploadedfile'),
        ),
        migrations.AddField(
            model_name='taskcategory',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category/project this task belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.taskcategory'),
        ),
        migrations.AddField(
            model_name='tasktag',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for flexible categorization', related_name='tasks', to='accounts.tasktag'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority_score'], name='accounts_ta_priorit_0b43e9_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_recurring'], name='accounts_ta_is_recu_bed2c1_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['parent_task'], name='accounts_ta_parent__561966_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'is_deleted', 'status'], name='accounts_ta_created_87bc60_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_by', 'is_deleted', 'complete_by_date'], name='accounts_ta_created_2db7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category', 'is_deleted'], name='accounts_ta_categor_a6412b_idx'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='default_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='accounts.taskcategory'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='default_tags',
            field=models.ManyToManyField(blank=True, related_name='templates', to='accounts.tasktag'),
        ),
        migrations.AddField(
            model_name='timelog',
            name='logged_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timelog',
            name='task',
            field=models.ForeignKey(help_text='Task this time entry is for', on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='accounts.task'),
        ),
        migrations.AddIndex(
            model_name='taskattachment',
            index=models.Index(fields=['task'], name='accounts_ta_task_id_22f7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcategory',
            index=models.Index(fields=['created_by', 'is_deleted'], name='accounts_ta_created_b95104_idx'),
        ),
        migrations.AddIndex(
            model_name='taskcategory',
            index=models.Index(fields=['display_order'], name='accounts_ta_display_e56377_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('created_by', 'name'), name='unique_category_per_user'),
        ),
        migrations.AddIndex(
            model_name='tasktag',
            index=models.Index(fields=['created_by'], name='accounts_ta_created_71684a_idx'),
        ),
        migrations.AddConstraint(
            model_name='tasktag',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_tag_per_user'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['created_by'], name='accounts_ta_created_7314fa_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['task'], name='accounts_ti_task_id_34a4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['logged_by'], name='accounts_ti_logged__1909c6_idx'),
        ),
        migrations.AddIndex(
            model_name='timelog',
            index=models.Index(fields=['start_time'], name='accounts_ti_start_t_4cce61_idx'),
        ),
    ]
