# Generated by Django 6.0 on 2026-01-04 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_recurringpattern_taskattachment_taskcategory_tasktag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminder',
            options={'verbose_name': 'Reminder', 'verbose_name_plural': 'Reminders'},
        ),
        migrations.RemoveIndex(
            model_name='reminder',
            name='accounts_re_frequen_be3a3b_idx',
        ),
        migrations.AddField(
            model_name='reminder',
            name='dismissed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='is_snoozed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_notified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='linked_finance',
            field=models.ForeignKey(blank=True, help_text='Finance product this reminder is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='accounts.financialproduct'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='linked_task',
            field=models.ForeignKey(blank=True, help_text='Task this reminder is linked to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='accounts.task'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='month_days',
            field=models.JSONField(blank=True, help_text='List of days (1-31) for monthly reminders', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='notification_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reminder',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Priority level', max_length=10),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_time',
            field=models.TimeField(blank=True, help_text='Specific time for reminder', null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('one_time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom Recurring'), ('linked_task', 'Linked to Task'), ('linked_finance', 'Linked to Payment')], default='one_time', help_text='Type of reminder', max_length=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='snoozed_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='weekdays',
            field=models.JSONField(blank=True, help_text='List of weekdays (0=Mon, 6=Sun) for weekly reminders', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='custom_repeat_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days interval for custom recurring', null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='daily', max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['reminder_type'], name='accounts_re_reminde_3fd21b_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['priority'], name='accounts_re_priorit_10f807_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['is_snoozed'], name='accounts_re_is_snoo_775abe_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['reminder_type', 'priority'], name='accounts_re_reminde_d815e0_idx'),
        ),
    ]
