# Generated by Django 6.0 on 2026-01-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_reminder_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('one_time', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom Recurring'), ('linked_task', 'Linked to Task'), ('linked_finance', 'Linked to Payment')], default='one_time', help_text='Type of reminder', max_length=20),
        ),
    ]
