# Generated by Django 6.0 on 2026-01-17 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_reminder_reminder_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(help_text='Date payment was made/received')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid in this transaction', max_digits=15)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('OTHER', 'Other')], help_text='Method of payment', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference number', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('receipt_file', models.FileField(blank=True, help_text='Receipt or proof of payment', null=True, upload_to='payment_receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Record',
                'verbose_name_plural': 'Payment Records',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='ledgertransaction',
            options={'ordering': ['-transaction_date', '-created_at'], 'verbose_name': 'Ledger Transaction', 'verbose_name_plural': 'Ledger Transactions'},
        ),
        migrations.RemoveIndex(
            model_name='ledgertransaction',
            name='accounts_le_created_1311c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledgertransaction',
            name='accounts_le_status_b58f91_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledgertransaction',
            name='accounts_le_transac_60ee54_idx',
        ),
        migrations.RemoveIndex(
            model_name='ledgertransaction',
            name='accounts_le_is_dele_c568e1_idx',
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='attachment',
            field=models.FileField(blank=True, help_text='Invoice, receipt, or supporting document', null=True, upload_to='ledger_attachments/'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='counterparty_contact',
            field=models.CharField(blank=True, help_text='Contact number of counterparty', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='counterparty_email',
            field=models.EmailField(blank=True, help_text='Email address of counterparty', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='due_date',
            field=models.DateField(blank=True, help_text='Due date for payment', null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='installment_number',
            field=models.PositiveIntegerField(blank=True, help_text='Installment number (e.g., 1 of 5)', null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice or receipt number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid so far', max_digits=15),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='parent_transaction',
            field=models.ForeignKey(blank=True, help_text='Parent transaction if this is an installment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='accounts.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('UPI', 'UPI'), ('CHEQUE', 'Cheque'), ('CARD', 'Card'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Transaction reference number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Amount remaining to be paid', max_digits=15),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text="Tags for categorization (e.g., ['supplies', 'materials'])"),
        ),
        migrations.AddField(
            model_name='ledgertransaction',
            name='total_installments',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of installments', null=True),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='completion_date',
            field=models.DateField(blank=True, help_text='Date when transaction was completed', null=True),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='counterparty',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIVABLE', 'Money to Receive'), ('RECEIVED', 'Money Received'), ('PAYABLE', 'Money to Pay'), ('PAID', 'Money Paid')], default='RECEIVABLE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['counterparty', 'is_deleted'], name='accounts_le_counter_19d374_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['created_by', 'transaction_date'], name='accounts_le_created_d5f497_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['status', 'due_date'], name='accounts_le_status_4f1e51_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['parent_transaction'], name='accounts_le_parent__c9d65e_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['transaction_type'], name='accounts_le_transac_7dd435_idx'),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='ledger_transaction',
            field=models.ForeignKey(help_text='Ledger transaction this payment is for', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.ledgertransaction'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['ledger_transaction', 'payment_date'], name='accounts_pa_ledger__4355da_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['created_by'], name='accounts_pa_created_1ee11f_idx'),
        ),
    ]
