# Generated by Django 6.0 on 2026-05-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_paymentrecord_alter_ledgertransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgertransaction',
            name='tab_name',
            field=models.CharField(blank=True, db_index=True, default='General', help_text="Sub-ledger tab within this counterparty (e.g. 'Loan', 'Daily')", max_length=100),
        ),
    ]
