# Generated by Django 6.0 on 2026-05-16 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_add_tab_name_to_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='counterparty_contact',
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='counterparty_email',
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='paymentrecord',
            name='receipt_file',
        ),
    ]
