# Generated by Django 6.0 on 2026-05-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_cleanup_unused_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ledgertransaction',
            name='accounts_le_parent__c9d65e_idx',
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='installment_number',
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='parent_transaction',
        ),
        migrations.RemoveField(
            model_name='ledgertransaction',
            name='total_installments',
        ),
    ]
