# Generated by Django 4.2.7 on 2026-08-15 (hand-edited to work around SQLite index-rebuild issue)
#
# The auto-generated RemoveField operations fail on SQLite because the old composite
# indexes on Reminder still reference 'created_by'. We work around this by using
# SeparateDatabaseAndState: the STATE side removes the fields and models as usual,
# while the DATABASE side simply drops each affected table directly (they are all
# legacy tables being fully deleted anyway — no FK dependencies to keep).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_installment_fields'),
    ]

    operations = [
        # -----------------------------------------------------------------------
        # Use SeparateDatabaseAndState to bypass SQLite index-rebuild limitation:
        #   - state_operations: what Django's migration framework should remember
        #   - database_operations: raw SQL that actually touches the DB
        # -----------------------------------------------------------------------
        migrations.SeparateDatabaseAndState(
            # Django state: remove FK fields first (needed to allow DeleteModel),
            # then delete the models.
            state_operations=[
                migrations.RemoveField(model_name='reminder', name='created_by'),
                migrations.RemoveField(model_name='reminder', name='linked_finance'),
                migrations.RemoveField(model_name='reminder', name='linked_task'),
                migrations.RemoveField(model_name='task', name='category'),
                migrations.RemoveField(model_name='task', name='created_by'),
                migrations.RemoveField(model_name='task', name='parent_task'),
                migrations.RemoveField(model_name='task', name='recurring_parent'),
                migrations.RemoveField(model_name='task', name='recurring_pattern'),
                migrations.RemoveField(model_name='task', name='tags'),
                migrations.RemoveField(model_name='taskattachment', name='task'),
                migrations.RemoveField(model_name='taskattachment', name='uploaded_file'),
                migrations.RemoveField(model_name='taskcategory', name='created_by'),
                migrations.RemoveField(model_name='tasktag', name='created_by'),
                migrations.RemoveField(model_name='tasktemplate', name='created_by'),
                migrations.RemoveField(model_name='tasktemplate', name='default_category'),
                migrations.RemoveField(model_name='tasktemplate', name='default_tags'),
                migrations.RemoveField(model_name='timelog', name='logged_by'),
                migrations.RemoveField(model_name='timelog', name='task'),
                migrations.RemoveField(model_name='uploadedfile', name='owner'),
                migrations.DeleteModel(name='RecurringPattern'),
                migrations.DeleteModel(name='Reminder'),
                migrations.DeleteModel(name='Task'),
                migrations.DeleteModel(name='TaskAttachment'),
                migrations.DeleteModel(name='TaskCategory'),
                migrations.DeleteModel(name='TaskTag'),
                migrations.DeleteModel(name='TaskTemplate'),
                migrations.DeleteModel(name='TimeLog'),
                migrations.DeleteModel(name='UploadedFile'),
            ],
            # Database: drop the physical tables directly (no index-rebuild needed).
            database_operations=[
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_reminder;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_task;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_task_tags;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_taskattachment;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_taskcategory;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_tasktag;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_tasktemplate;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_tasktemplate_default_tags;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_recurringpattern;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_timelog;",
                    migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "DROP TABLE IF EXISTS accounts_uploadedfile;",
                    migrations.RunSQL.noop,
                ),
            ],
        ),
        # profile_picture removal is a simple field on userprofile — no index conflict
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
