# Generated by Django 4.2.7 on 2026-08-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_installment_fields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurringPattern',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskAttachment',
        ),
        migrations.DeleteModel(
            name='TaskCategory',
        ),
        migrations.DeleteModel(
            name='TaskTag',
        ),
        migrations.DeleteModel(
            name='TaskTemplate',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]

