# Generated by Django 4.2.7 on 2026-08-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_remove_task_and_reminder_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='mode_detail',
        ),
    ]
