# Generated by Django 4.2.7 on 2026-08-15 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0031_remove_profile_picture_task_reminder_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Account name, e.g. 'HDFC Bank', 'Cash', 'Paytm Wallet'", max_length=100)),
                ('account_type', models.CharField(choices=[('bank', 'Bank'), ('cash', 'Cash'), ('wallet', 'Wallet')], default='bank', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Category name, e.g. 'Food', 'Rent', 'Salary'", max_length=100)),
                ('category_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SplitPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g. 'New Phone - No Cost EMI'", max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('num_months', models.PositiveIntegerField(help_text='Number of installments')),
                ('start_month', models.DateField(help_text='First day of month when installments start')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='split_plans', to='accounts.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Split Plan',
                'verbose_name_plural': 'Split Plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Bike Loan'", max_length=100)),
                ('principal', models.DecimalField(decimal_places=2, help_text='Total principal - informational only', max_digits=15)),
                ('monthly_emi', models.DecimalField(decimal_places=2, help_text='Fixed EMI amount per month, user-entered', max_digits=15)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='accounts.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'SIP - Mutual Fund X'", max_length=100)),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Fixed monthly contribution, user-entered', max_digits=15)),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='accounts.account')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('loan_emi', 'Loan EMI'), ('investment_contribution', 'Investment Contribution'), ('split_installment', 'Split Installment')], default='expense', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Always positive; direction is determined by entry_type', max_digits=15)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(help_text='Account this entry is charged to / credited from', on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, help_text='Only for expense/income entries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='accounts.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('linked_investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_entries', to='accounts.investment')),
                ('linked_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emi_entries', to='accounts.loan')),
                ('linked_split', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installment_entries', to='accounts.splitplan')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['created_by', 'date'], name='accounts_en_created_628a8d_idx'), models.Index(fields=['created_by', 'entry_type'], name='accounts_en_created_167831_idx'), models.Index(fields=['created_by', 'account'], name='accounts_en_created_77137d_idx'), models.Index(fields=['created_by', 'category'], name='accounts_en_created_695913_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_by', 'is_active'], name='accounts_ca_created_1c0f39_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['created_by', 'category_type'], name='accounts_ca_created_1a9f62_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_by', 'is_active'], name='accounts_ac_created_1c1bb2_idx'),
        ),
    ]
