# Generated by Django 4.2.7 on 2026-08-15 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0033_data_migrate_transactions_to_entries'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Contact',
                'verbose_name_plural': 'Ledger Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('given', 'Given (You lent money)'), ('taken', 'Taken (You borrowed money)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('settled', 'Settled')], default='open', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.ledgercontact')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ledger Entry',
                'verbose_name_plural': 'Ledger Entries',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['created_by', 'contact'], name='accounts_le_created_d461a0_idx'), models.Index(fields=['created_by', 'status'], name='accounts_le_created_080a46_idx')],
            },
        ),
    ]
