# Generated by Django 4.2.7 on 2026-08-15 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0034_add_ledger_contact_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='StagingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('phonepe', 'PhonePe'), ('gpay', 'Google Pay'), ('other', 'Other')], max_length=20)),
                ('original_txn_id', models.CharField(blank=True, help_text='Transaction ID from CSV to prevent duplicates', max_length=100)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('loan_emi', 'Loan EMI'), ('investment_contribution', 'Investment Contribution'), ('split_installment', 'Split Installment')], max_length=30)),
                ('raw_description', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('committed', 'Committed'), ('duplicate', 'Duplicate (Skipped)')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staging Entry',
                'verbose_name_plural': 'Staging Entries',
                'ordering': ['date', 'created_at'],
                'indexes': [models.Index(fields=['created_by', 'status'], name='accounts_st_created_446fba_idx'), models.Index(fields=['original_txn_id'], name='accounts_st_origina_a87953_idx')],
            },
        ),
    ]
